### PR TITLE
Number of People in Space

### PR DESCRIPTION
**Pull request by dralan92**
Number of People in Space

### CODE REVIEW

**Comment by caiodias** [comment]
Why who did the code is one person and the last changed was made by the PR author?

**Comment by dralan92** [comment]
Everything was done by me.

**Comment by caiodias** [comment]
Isn't what the commit log says. Two accounts were used.

**Comment by dralan92** [comment]
both are my accounts.
I was not sure about making PR head to develop branch.So i did some experiments with it.

**Pull request merged**
