### PR TITLE
Calling Marvel character 

### PR DESCRIPTION
**Pull request by mpanday**
This is my project for calling Marvel character.
Manu

### CODE REVIEW

**Comment by caiodias** [comment]
Please move all your projects files to a new folder using your github account username. It will be something like: student, student/css, student/js

**Comment by caiodias** [comment]
I'm not sure if the link `./manupanday/index.html` will work. Did you test?
Everything else seems to be good.

**Comment by caiodias** [comment]
Well done

**Comment by mpanday** [comment]
Yeah I tested it worked on my machine

**Pull request merged**
